### ISSUE TITLE
Considering replacing PHAMLP with jade.php

### ISSUE THREAD

**Issue by stefanoverna** [welaika/wordless#111]
I've just stumbled upon https://github.com/everzet/jade.php, which is a nice Slim/Jade PHP ripoff. Seems quite nice and even DRYer. I was considering to add it as an alternative Wordless templating solution (maybe make it the default one).

One gotcha: it's compatible with PHP 5.3+.

Any other HAML/Slim/Jade PHP ripoffs around there?

**Comment by mukkoo** [comment]
Too old discussion. I close it.
Both projects (Phamlp and jade) are not developed by years.
