### ISSUE TITLE
javascript_include_tag serves /theme/assets/javascript  folder

### ISSUE THREAD

**Issue by lasdolphin** [welaika/wordless#193]
when i call javascript_include_tag i'm getting following error

"WordlessCompileException: [0]: File '/Users/lasdolphin/dev/sites/sokolniki/wp-content/themes/sokolniki/theme/assets/javascripts/jquery.mousewheel-3.0.6.pack.(js|js.coffee)' does not exists!

Output error:

" jquery.mousewheel-3.0.6.pack.js:1:1

"WordlessCompileException: [0]: File '/Users/lasdolphin/dev/sites/sokolniki/wp-content/themes/sokolniki/theme/assets/javascripts/jquery.fancybox.pack.(js|js.coffee)' does not exists!

Output error:

" jquery.fancybox.pack.js:1:1

"WordlessCompileException: [0]: File '/Users/lasdolphin/dev/sites/sokolniki/wp-content/themes/sokolniki/theme/assets/javascripts/jquery.fancybox-thumbs.(js|js.coffee)' does not exists!

Output error:

"

For some  reason it doesn't serves static js folder.

**Comment by pioneerskies** [comment]
Could you paste your code, please?
