### ISSUE TITLE
"You do not have sufficient permissions to access this page." when creating new theme

### ISSUE THREAD

**Issue by rjfranco** [welaika/wordless#196]
After a fresh installation, from within the wordpress ui when I click "Create a new Wordless theme" wordpress traverses to the path /wp-admin/themes.php?page=create_wordless_theme and I am told I don't have sufficient permission to access the page.

**Comment by crtvhd** [comment]
+1

**Comment by mukkoo** [comment]
Hi, have you check wordless plugin folder permissions?

**Comment by rjfranco** [comment]
I had, but that's a bit of a vague question, which folder? What should permissions be set to? I tried to find documentation offering suggestions, but at the time I couldn't.

**Comment by wushan** [comment]
same problem

**Comment by namuit** [comment]
Hi. Can you check with the last version (0.5.5) if the problem has been solved? The commit 62f8222 should correct the link used to go to create a new theme.
