### ISSUE TITLE
Working with plugins that do their own routing

### ISSUE THREAD

**Issue by desmillicious** [welaika/wordless#199]
Hi there I am working with a plugin - [Time.ly Event Calendar](https://wordpress.org/plugins/all-in-one-event-calendar/) - that does it's own routing.

The routing is non-standard with it's own MVC framework, db tables and php on the fly generated views for it's custom post type `ai1ec_event`. There is no static php template for a particular view that I can point to for the `ai1ec_event` single post view, which is what I have done in the past to handle e-commerce 

Is there a way to revert to wordpress routing for specific views?

eg: in `index.php` of the wordless theme...

``` php
if (is_singular() && is_post_type("ai1ec_event")) {
   revert to wordpress routing
}
```

**Comment by pioneerskies** [comment]
Oh gosh! Never ever thought about such a situation...but: Wordless shouldn't alter the wordpress routing per se: it uses conditional tags based on the Wordpress routing just to print on screen. Default themes usually have a get_template_part() in the index.php, while we have a custom render function.

Usually plugins such that - but I don't know Time.ly at all, so sorry if Im wrong - hooks themselves to something like the_content()...I see from the documentation of the plugin that it has builtin shortcodes support. Why don't you try to build a template with a simple do_shortcode() function inside or a the_content() dropping the shortcode in the the page editor?

I can't see more than this lurking into the documentation on the page you linked.

Cheers
