### ISSUE TITLE
wordless themes?

### ISSUE THREAD

**Issue by fauno** [welaika/wordless#200]
are there any wordless themes available? or a default theme you can use as a base for new ones?  or a way to convert existing wordpress themes?  i really like the ideas of wordless but i'm not sure i'd have to start from scratch :P

**Comment by pioneerskies** [comment]
Wordless comes with a predefined vanilla theme to boost the initial bootstrap
In the image below there's how to generate a new vanilla theme

![image](https://cloud.githubusercontent.com/assets/904690/13722716/ce07f458-e84e-11e5-9a37-7bf767d3d0c5.png)

Cheers :)

**Comment by pioneerskies** [comment]
Oh...just saying: the theme is useful just for the code organization, but it's just a sandbox to build themes from scratch. We'd always done themes from scratch.

**Comment by fauno** [comment]
great, thanks!
