### ISSUE TITLE
Issue related to wordless website

### ISSUE THREAD

**Issue by anishojha** [welaika/wordless#234]
Hi, this issue is not for WordLess, but it's for wordless website, please see the screenshot

URL: https://www.wptools.it/wordless

![wordless-website](https://user-images.githubusercontent.com/24322181/56084079-5a2d7f00-5e4b-11e9-8142-6c977697beaf.png)

**Comment by mukkoo** [comment]
@anishojha now it works. 
Thanks

**Comment by pioneerskies** [comment]
@mukkoo what do you mean by it works? I see the same error message that was reported

**Comment by pioneerskies** [comment]
I'm going simply to remove the no more available asciicast. Let me know if you had found different solution
