### ISSUE TITLE
Error loading css on clean install

### ISSUE THREAD

**Issue by linx8** [welaika/wordless#253]
Hello,
I'm getting the following errors on a fresh install. It looks like its reading the css files as HTML for some reason. I haven't changed any settings and followed the install instructions. 

![image](https://user-images.githubusercontent.com/20533332/82281560-faea5880-99d4-11ea-81cf-e96736e3da96.png)

Thanks

**Comment by pioneerskies** [comment]
Hello,

I'm trying to reproduce on a clean theme, but I cannot.

You have a syntax error in your page (`Unexpected token '<'`); would you mind to try to find out where it is happening? I need a path to follow :)

**Comment by linx8** [comment]
It looks to be a compiling or webpack issue, as its reading the css file incorrectly (as per the warning). When I look at the file it returns html:

![image](https://user-images.githubusercontent.com/20533332/82324375-dfa33b80-9a1c-11ea-8dcc-4701317671d7.png)

I am using node v12.13.1 and have made no changes so far. Any ideas?

**Comment by pioneerskies** [comment]
Not yet. But trying to `yarn build:dev` should confirm that you're having SCSS compilation issues and hopefully it should give us a clearer error in console. I hope to be able to catch something from that output :)

Lemme just ask: I'm reading

> This site uses the Google Analytics [...]

from your source code. Is that injected by a plugin? Also the `x-ua-compatible` seems to not be from the boilerplate template. Are you sure you are trying from within a freshly bootstrapped theme? Just trying to search some starting point here :D

**Comment by linx8** [comment]
running `yarn build:dev` doesn't throw any errors and builds successfully. Its really weird. I disabled all wordpress plugins (besides wordless) and still getting the same error.

![image](https://user-images.githubusercontent.com/20533332/82389619-0777bb00-9a80-11ea-817a-7ff7738d6166.png)

**Comment by pioneerskies** [comment]
Hey sorry: my replies became all but prompt.

I've a proposal: would you mind to send me your theme zipped? If it's freshly bootstrapped you should not have sensitive/private data in it and I'd be able to just drop it down in my dev env and debug it.

Let me know!
