### ISSUE TITLE
error running Yarn run server

### ISSUE THREAD

**Issue by renansantos** [welaika/wordless#264]
Hello!
I am getting the following error when trying to start the server from a fresh install:
ENOENT: no such file or directory, open 'start'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by pioneerskies** [comment]
Hello there! I'd be glad to help, but I surely need more context. How did you installed? The error is from the `yarn server` command? Are you on version 4.1, that's right? `yarn setup` went 100% flawlessly?

**Comment by pioneerskies** [comment]
Oh my...I've an idea @renansantos : open `package.json` inside your theme and edit the following

```
"server": "npx nf start",
```

to the following

```
"server": "nf start",
```

It seems a good try to me. Let me know :)

**Comment by renansantos** [comment]
Thanks for the support!
I uninstalled nvm and node, installed it all again and it worked!

**Comment by pioneerskies** [comment]
Nice to read that.

All the best
