### ISSUE TITLE
Error in render_helper.php file occurring in render_template func via ensure_dir func

### ISSUE THREAD

**Issue by arun744-newscorp** [welaika/wordless#284]
In render_helper.php file in function error was identified: Ouch!! It seems that the /var/www/wp-content/themes/<>/tmp

ensure_dir function sometimes cannot override the tmp folder permission to writeable, some server forbid the chmod action. Hence we compile our files via CLI during CI build process, this generates files in tmp DIR. Now I have corrected version of ensure_dir function test in our environment to check both compiled files in tmp and also create tmp if didn't exist this applies for both scenario.

Secondly we have filter 'wordless_environment' to override the environment.

PR: https://github.com/welaika/wordless/pull/283

**Comment by pioneerskies** [comment]
Will schedule to check this one for sure. In the meantime thank you very much for the PR.
